[package]
name = "conn_mon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["derive", "cargo"] }
env_logger = "0.10.0"
log = "0.4.19"
regex = "1.9.1"
rstest = "0.18.1"
